const copy = {
en:{
"nav.lab":"The Lab","nav.about":"About","nav.team":"Meet the Lab","nav.contact":"Contact",
"hero.eyebrow":"INDEPENDENT PRODUCT LAB · OTTAWA, CANADA","hero.title":"Small experiments.<br>Real problems.<br><em>Useful things.</em>","hero.body":"Ghita Labs is an independent product lab. I look for small, recurring problems in the way people work, understand them properly, and build focused software when there’s something genuinely worth fixing.","hero.cta":"Enter the lab",
"experiments.kicker":"EXPERIMENT LOG","experiments.intro":"Not every experiment becomes a product. That’s the point.",
"exp1.status":"PAUSED","exp1.body":"An exploration of initiation friction: the gap between knowing what needs to be done and actually starting. The concept exposed a measurement problem that made the original product thesis difficult to validate reliably.","exp1.note":"Status: postponed, not erased. The research remains useful, but the original direction is not being actively built.",
"exp2.status":"RESEARCH","exp2.body":"Exploring a better way to understand and verify Shopify Payments activity, especially when the numbers in reports and the books don’t line up as cleanly as they should.","exp2.note":"Currently speaking with bookkeepers and business owners to understand reconciliation workflows, edge cases and what is actually worth automating.","exp2.link":"I work with Shopify Payments →","common.notes":"Lab notes",
"about.kicker":"INSIDE THE LAB","about.title":"Hi, I’m Ghita.","about.p1":"My work sits somewhere between business problems and technical systems, which means I spend a lot of time looking at the awkward space between “this should be simple” and “why are we still doing this manually?”","about.p2":"Ghita Labs is where I explore those problems independently and, when one proves worth solving, turn it into something useful.","about.business":"Business","about.businessText":"Background in management and marketing.","about.systems":"Systems","about.systemsText":"Professional experience translating messy business needs into functional and technical solutions.","about.tech":"Technology & data","about.techText":"Hands-on experience with data, APIs, Python, cloud and software systems.","about.equipment":"Open the equipment drawer","about.independent":"Ghita Labs is an independent personal project and is not affiliated with or endorsed by my employer.",
"team.kicker":"MEET THE LAB","team.title":"Meet the team.<br>Yes, it’s all Ghita.","team.analyst":"The Analyst","team.analystText":"Talks to people, pulls problems apart and asks an unreasonable number of “why?” questions.","team.builder":"The Builder","team.builderText":"Turns the useful parts into prototypes, automations and small pieces of software.","team.skeptic":"The Skeptic","team.skepticText":"Usually the one asking whether anyone actually needs what the other two are trying to build.","team.ghitaAgain":"Ghita, again","team.founder":"The Founder","team.founderText":"Makes the final call and occasionally reminds everyone that Ghita Labs has exactly one person behind it.","team.transparency":"Ghita Labs is an independent one-person product lab founded by Ghita El Belghiti.",
"contact.kicker":"TALK TO THE LAB","contact.title":"Got something weird that shouldn’t still be this difficult?","contact.body":"If you work with Shopify Payments, have a recurring workflow that makes you think “there has to be a better way,” or simply want to say hello, I’d like to hear from you.","contact.cta":"Send a note","contact.note":"No mailing list. No sales sequence. Just a real inbox.","footer.line":"Independent product lab · Ideas into impact."
},
fr:{
"nav.lab":"Le labo","nav.about":"À propos","nav.team":"Dans le labo","nav.contact":"Contact",
"hero.eyebrow":"LABORATOIRE PRODUIT INDÉPENDANT · OTTAWA, CANADA","hero.title":"Petites expériences.<br>Vrais problèmes.<br><em>Des choses utiles.</em>","hero.body":"Ghita Labs est un laboratoire produit indépendant. J’y cherche de petits problèmes récurrents dans notre façon de travailler, je prends le temps de les comprendre, puis je construis quelque chose quand il y a vraiment quelque chose à régler.","hero.cta":"Entrer dans le labo",
"experiments.kicker":"CARNET D’EXPÉRIENCES","experiments.intro":"Toutes les expériences ne deviennent pas des produits. C’est justement le principe.",
"exp1.status":"EN PAUSE","exp1.body":"Une exploration de la friction au démarrage : cet écart entre savoir ce qu’on doit faire et réussir à commencer. Le concept a fait ressortir un problème de mesure qui rendait la thèse produit initiale difficile à valider de façon fiable.","exp1.note":"Statut : reporté, pas effacé. La recherche reste utile, mais cette direction n’est pas en développement actif.",
"exp2.status":"RECHERCHE","exp2.body":"J’explore une meilleure façon de comprendre et vérifier l’activité Shopify Payments, surtout quand les chiffres des rapports et ceux des livres ne s’alignent pas aussi proprement qu’ils le devraient.","exp2.note":"Je parle actuellement avec des teneurs de livres et des propriétaires d’entreprise pour comprendre leurs méthodes de rapprochement, les cas qui posent problème et ce qui mérite réellement d’être automatisé.","exp2.link":"Je travaille avec Shopify Payments →","common.notes":"Notes du labo",
"about.kicker":"DANS LE LABO","about.title":"Moi, c’est Ghita.","about.p1":"Mon travail se situe quelque part entre les problèmes d’affaires et les systèmes techniques. Je passe donc pas mal de temps dans cette zone étrange entre « ça devrait être simple » et « pourquoi est-ce qu’on fait encore ça à la main ? ».","about.p2":"Ghita Labs, c’est l’endroit où j’explore ces problèmes de façon indépendante et où, lorsqu’un problème mérite vraiment d’être réglé, j’essaie d’en faire quelque chose d’utile.","about.business":"Affaires","about.businessText":"Formation en gestion et en marketing.","about.systems":"Systèmes","about.systemsText":"Expérience professionnelle à transformer des besoins d’affaires parfois brouillons en solutions fonctionnelles et techniques claires.","about.tech":"Technologie et données","about.techText":"Expérience pratique avec les données, les API, Python, le cloud et les systèmes logiciels.","about.equipment":"Ouvrir le tiroir à outils","about.independent":"Ghita Labs est un projet personnel indépendant, sans affiliation ni approbation de mon employeur.",
"team.kicker":"DANS LE LABO","team.title":"L’équipe du labo.<br>Oui, c’est toujours Ghita.","team.analyst":"L’analyste","team.analystText":"Parle aux gens, démonte les problèmes pièce par pièce et pose probablement beaucoup trop de « pourquoi ? ».","team.builder":"La bâtisseuse","team.builderText":"Transforme ce qui vaut la peine d’être gardé en prototypes, automatisations et petits outils logiciels.","team.skeptic":"La sceptique","team.skepticText":"C’est généralement elle qui demande si quelqu’un a réellement besoin de ce que les deux autres essaient de construire.","team.ghitaAgain":"Ghita, encore","team.founder":"La fondatrice","team.founderText":"Tranche quand il faut trancher et rappelle parfois aux autres que Ghita Labs tient, en réalité, sur une seule personne.","team.transparency":"Ghita Labs est un laboratoire produit indépendant fondé et opéré par Ghita El Belghiti.",
"contact.kicker":"PARLER AU LABO","contact.title":"Tu es tombé sur un problème qui ne devrait vraiment plus être aussi compliqué ?","contact.body":"Si tu travailles avec Shopify Payments, si tu as un processus récurrent qui te fait penser « il doit bien y avoir une meilleure façon », ou si tu veux simplement me parler d’un problème étrange, écris-moi.","contact.cta":"Écrire au labo","contact.note":"Pas d’infolettre. Pas de séquence de vente. Juste une vraie boîte courriel.","footer.line":"Laboratoire produit indépendant · Ideas into impact."
}};
function setLang(lang){
 document.documentElement.lang=lang;
 document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(copy[lang][k])el.innerHTML=copy[lang][k]});
 document.querySelectorAll(".lang-btn").forEach(b=>{const active=b.dataset.lang===lang;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});
 localStorage.setItem("ghita-labs-lang",lang);
 document.title=lang==="fr"?"Ghita Labs — Laboratoire produit indépendant":"Ghita Labs — Independent product lab";
}
document.querySelectorAll(".lang-btn").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
document.querySelectorAll(".reveal-btn").forEach(btn=>btn.addEventListener("click",()=>{
 const card=btn.closest(".experiment-card"),open=card.classList.toggle("open");btn.setAttribute("aria-expanded",String(open));
}));
document.getElementById("year").textContent=new Date().getFullYear();
setLang(localStorage.getItem("ghita-labs-lang")||((navigator.language||"").startsWith("fr")?"fr":"en"));
