const copy = {
en:{
"nav.lab":"The Lab","nav.about":"About","nav.team":"Meet the Lab","nav.contact":"Contact",
"hero.eyebrow":"INDEPENDENT PRODUCT LAB · OTTAWA, CANADA","hero.title":"Small experiments.<br>Real problems.<br><em>Useful things.</em>","hero.body":"Ghita Labs is an independent product lab. I look for small, recurring problems in the way people work, understand them properly, and build focused software when there’s something genuinely worth fixing.","hero.cta":"Enter the lab",
"experiments.kicker":"EXPERIMENT LOG","experiments.intro":"Not every experiment becomes a product. That’s the point.",
"exp1.status":"PAUSED","exp1.body":"An exploration of initiation friction: the gap between knowing what needs to be done and actually starting. The concept exposed a measurement problem that made the original product thesis difficult to validate reliably.","exp1.note":"Status: postponed, not erased. The research remains useful, but the original direction is not being actively built.",
"exp2.status":"RESEARCH","exp2.body":"Exploring a better way to understand and verify Shopify Payments activity, especially when the numbers in reports and the books don’t line up as cleanly as they should.","exp2.note":"Currently speaking with bookkeepers and business owners to understand reconciliation workflows, edge cases and what is actually worth automating.","exp2.link":"I work with Shopify Payments →","common.notes":"Lab notes",
"about.kicker":"INSIDE THE LAB","about.title":"Hi, I’m Ghita.","about.p1":"My background sits between business, data and technology. I studied management and marketing, then somehow ended up working with requirements, data exchanges, APIs, Python, reporting and the systems behind them.","about.p2":"Most of my day-to-day work starts the same way: someone has a problem, several systems or people are involved, and the obvious answer usually isn’t the whole answer. So I ask questions, pull the workflow apart, follow the data and work with the people who actually use or build the thing. Ghita Labs is where I do that independently.","about.business":"Business","about.businessText":"Background in management and marketing.","about.systems":"Analysis & delivery","about.systemsText":"I work across business and technical teams to clarify requirements, trace dependencies and move solutions through testing and delivery.","about.tech":"Technology & data","about.techText":"Hands-on work with reporting, data validation, automation, APIs and cloud-based data workflows.","about.equipment":"Open the equipment drawer","about.independent":"Ghita Labs is an independent personal project and is not affiliated with or endorsed by my employer.",
"team.kicker":"MEET THE LAB","team.title":"Meet the team.<br>Yes, it’s all Ghita.","team.analyst":"The Analyst","team.analystText":"Finds the actual problem. Talks to people, maps what happens between systems and follows the data until the messy part starts making sense.","team.builder":"The Builder","team.builderText":"Turns the useful part into something real. Prototypes, experiments and small pieces of software, enough to find out whether an idea actually works before making it bigger.","team.skeptic":"The Skeptic","team.skepticText":"Keeps the other two from getting carried away. Asks whether the problem is real, whether anyone cares enough to change what they’re doing and whether this actually needs to exist.","team.siriusRole":"Quality Control.","team.siriusText":"Contributes absolutely nothing to the code. Occasionally attends meetings, frequently walks across the keyboard and maintains extremely high standards for workplace comfort.","team.transparency":"Three roles, one founder. Ghita Labs is an independent one-person product lab founded by Ghita El Belghiti.",
"contact.kicker":"TALK TO THE LAB","contact.title":"Got something weird that shouldn’t still be this difficult?","contact.body":"If you work with Shopify Payments, have a recurring workflow that makes you think “there has to be a better way,” or simply want to say hello, I’d like to hear from you.","contact.cta":"Send a note","contact.note":"No mailing list. No sales sequence. Just a real inbox.","footer.line":"Independent product lab · Ideas into impact."
},
fr:{
"nav.lab":"Le labo","nav.about":"À propos","nav.team":"Dans le labo","nav.contact":"Contact",
"hero.eyebrow":"LABORATOIRE PRODUIT INDÉPENDANT · OTTAWA, CANADA","hero.title":"Petites expériences.<br>Vrais problèmes.<br><em>Des choses utiles.</em>","hero.body":"Ghita Labs est un laboratoire produit indépendant. J’y cherche de petits problèmes récurrents dans notre façon de travailler, je prends le temps de les comprendre, puis je construis quelque chose quand il y a vraiment quelque chose à régler.","hero.cta":"Entrer dans le labo",
"experiments.kicker":"CARNET D’EXPÉRIENCES","experiments.intro":"Toutes les expériences ne deviennent pas des produits. C’est justement le principe.",
"exp1.status":"EN PAUSE","exp1.body":"Une exploration de la friction au démarrage : cet écart entre savoir ce qu’on doit faire et réussir à commencer. Le concept a fait ressortir un problème de mesure qui rendait la thèse produit initiale difficile à valider de façon fiable.","exp1.note":"Statut : reporté, pas effacé. La recherche reste utile, mais cette direction n’est pas en développement actif.",
"exp2.status":"RECHERCHE","exp2.body":"J’explore une meilleure façon de comprendre et vérifier l’activité Shopify Payments, surtout quand les chiffres des rapports et ceux des livres ne s’alignent pas aussi proprement qu’ils le devraient.","exp2.note":"Je parle actuellement avec des teneurs de livres et des propriétaires d’entreprise pour comprendre leurs méthodes de rapprochement, les cas qui posent problème et ce qui mérite réellement d’être automatisé.","exp2.link":"Je travaille avec Shopify Payments →","common.notes":"Notes du labo",
"about.kicker":"DANS LE LABO","about.title":"Moi, c’est Ghita.","about.p1":"Mon parcours se situe entre les affaires, les données et la technologie. J’ai étudié la gestion et le marketing, puis je me suis retrouvée à travailler avec des exigences, des échanges de données, des API, Python, du reporting et les systèmes derrière tout ça.","about.p2":"Mon travail commence souvent de la même façon : quelqu’un a un problème, plusieurs personnes ou systèmes sont impliqués, et la réponse évidente n’est généralement pas toute l’histoire. Alors je pose des questions, je démonte le workflow, je suis les données et je travaille avec les personnes qui utilisent ou construisent réellement la solution. Ghita Labs, c’est l’endroit où je fais ça de façon indépendante.","about.business":"Affaires","about.businessText":"Formation en gestion et en marketing.","about.systems":"Analyse et livraison","about.systemsText":"Je travaille entre équipes d’affaires et techniques pour clarifier les besoins, suivre les dépendances et accompagner les solutions jusqu’aux tests et à la livraison.","about.tech":"Technologie et données","about.techText":"Travail pratique en reporting, validation de données, automatisation, API et workflows de données dans le cloud.","about.equipment":"Ouvrir le tiroir à outils","about.independent":"Ghita Labs est un projet personnel indépendant, sans affiliation ni approbation de mon employeur.",
"team.kicker":"DANS LE LABO","team.title":"L’équipe du labo.<br>Oui, c’est toujours Ghita.","team.analyst":"L’analyste","team.analystText":"Cherche le vrai problème. Parle aux gens, cartographie ce qui se passe entre les systèmes et suit les données jusqu’à ce que le bazar commence à avoir du sens.","team.builder":"La bâtisseuse","team.builderText":"Transforme la partie utile en quelque chose de réel. Des prototypes, des expériences et de petits logiciels, juste assez pour savoir si l’idée fonctionne avant de la faire grossir.","team.skeptic":"La sceptique","team.skepticText":"Empêche les deux autres de s’emballer. Demande si le problème est réel, si quelqu’un s’en soucie assez pour changer ses habitudes et si cette chose a vraiment besoin d’exister.","team.siriusRole":"Contrôle qualité.","team.siriusText":"Ne contribue absolument rien au code. Assiste parfois aux réunions, marche régulièrement sur le clavier et maintient des standards extrêmement élevés en matière de confort au travail.","team.transparency":"Trois rôles, une fondatrice. Ghita Labs est un laboratoire produit indépendant fondé et opéré par Ghita El Belghiti.",
"contact.kicker":"PARLER AU LABO","contact.title":"Tu es tombé sur un problème qui ne devrait vraiment plus être aussi compliqué ?","contact.body":"Si tu travailles avec Shopify Payments, si tu as un processus récurrent qui te fait penser « il doit bien y avoir une meilleure façon », ou si tu veux simplement me parler d’un problème étrange, écris-moi.","contact.cta":"Écrire au labo","contact.note":"Pas d’infolettre. Pas de séquence de vente. Juste une vraie boîte courriel.","footer.line":"Laboratoire produit indépendant · Ideas into impact."
}};
function setLang(lang){
 document.documentElement.lang=lang;
 document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(copy[lang][k])el.innerHTML=copy[lang][k]});
 document.querySelectorAll(".lang-btn").forEach(b=>{const active=b.dataset.lang===lang;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});
 localStorage.setItem("ghita-labs-lang",lang);
 document.title=lang==="fr"?"Ghita Labs — Laboratoire produit indépendant":"Ghita Labs — Independent product lab";
}
document.querySelectorAll(".lang-btn").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
document.querySelectorAll(".reveal-btn").forEach(btn=>btn.addEventListener("click",()=>{
 const card=btn.closest(".experiment-card"),open=card.classList.toggle("open");btn.setAttribute("aria-expanded",String(open));
}));
document.getElementById("year").textContent=new Date().getFullYear();
setLang(localStorage.getItem("ghita-labs-lang")||((navigator.language||"").startsWith("fr")?"fr":"en"));
